[package]
name = "seqmap"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
plotters = "0.3.7"
rayon = "1.11.0"
tabled = "0.20.0"
